FROM python:3
LABEL authors="bogdani"

COPY linkedlist/requirements.txt /app/requirements.txt

WORKDIR /app

ENV PYTHONPATH="${PYTHONPATH}:/app"

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python3", "linkedlist/linkedlist_main.py"]